Feature front
Lugdunum3D/LugBench-server pull request #4
Opened 2017-02-24 15:58 UTC by Quentin01

Remake of #2 
Merge #3 first

2017-02-27 06:37 UTC, Quentin01 commented on app/index.js
> +	gpu.find().then((gpus) => {
There are indentation problems in that file (we use 4 spaces to indent)

2017-02-27 06:37 UTC, Quentin01 commented on server.js
> +server.use('/app', app);
Why do you want an `/app`? Or if you still want that, maybe redirect `/` to `/app`?

2017-04-18 17:57 UTC, yoannpicquenot requested changes
.floo files have to be removed

2017-04-18 17:57 UTC, yoannpicquenot submitted a review, later dismissed

2017-04-30 16:41 UTC, Quentin01 commented
Is it ready to be review?

2017-05-23 11:41 UTC, Quentin01 commented
@mapy69003 @cchardeau Does someone can answer my question? Is it ready to merge or not?

2017-05-24 15:29 UTC, mapy69003 commented
@Quentin01 Sorry, not yet

2017-05-24 21:48 UTC, mapy69003 commented
@Quentin01 ready to be reviewed

2017-07-31 09:45 UTC, Sumenia commented
@Quentin01 @saveman71 , you were both be assigned to review this PR since May 25. 
For the sake of the project, we need to merge this to dev/master asap. We cannot go on working on one single branch as the PR will only get bigger.

2017-10-12 13:45 UTC, closed without merging